---
site:
  title: Ansible Automation Platform, HashiCorp Terraform and Vault!
  url: https://rhpds.github.io/zt-ans-bu-hashi-aap/modules/index.html
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/summit-2026/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - require: ./content/lib/dev-mode.js
      enabled: false

output:
  dir: ./www
