---
type: showroom
tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
    external: false
  - name: "Terminal"
    url: /wetty_central
  - name: Wazuh
    url: https://wazuh-${guid}.${domain}
  - name: HashiCorp Vault
    url: https://vault-${guid}.${domain}/ui/vault/unseal
    external: true
