---
antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Verify ZTA Components and AAP Integration
    - name: module-02
      label: "Deploy application with short-lived credentials"
    - name: module-03
      label: "AAP Policy as Code: platform-gated patching"
    - name: module-02
      label: "SPIFFE-verified network VLAN management"
    - name: module-03
      label: "Automated incident response (Splunk → EDA → Vault)"

tabs:
  - name: Lab Topology
    url: https://dashboard-http-${guid}.${domain}
    external: false
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
    external: false
  - name: "Terminal"
    url: /wetty_central
  - name: IDM
    url: https://idm-https-${guid}.${domain}/ipa/ui/
    external: false
  - name: Netbox
    url: https://netbox-${guid}.${domain}
    external: false
  # - name: Keycloak
  #   url: https://keycloak-https-${guid}.${domain}
  #   external: true
  - name: OPA
    url: https://opa-http-${guid}.${domain}
    external: false
  - name: HashiCorp Vault
    url: https://vault-${guid}.${domain}/ui/vault/unseal
    external: true
  # - name: Wazuh
  #   url: https://wazuh-${guid}.${domain}
  #   external: false
  # - name: Gitea
  #   url: https://gitea-${guid}.${domain}/
  #   external: false
  - name: Splunk
    url: https://splunk-http-${guid}.${domain}
    external: true
  - name: Global Telemetry Platform
    url: https://app-http-${guid}.${domain}
    external: true
